### ISSUE TITLE
Add copy toast

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#126]
### Expected Behaviour
when user selects "copy" from generated variations or from favorites a toast appears to let user know that an action has happened

green success toast >> "copied to clipboard"

### Actual Behaviour

no toast

**Comment by coreydulimba-ad** [comment]
@askayastha22 i don't see a toast in the Favorites just on the variants. can you please add there

**Comment by askayastha22** [comment]
@coreydulimba-ad Forgot about the Favorites view. I will add it.

**Comment by coreydulimba-ad** [comment]
fixed
