### ISSUE TITLE
Prompt cards Titles do not wrap

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#153]
### Expected Behaviour

Card titles wrap

### Actual Behaviour

Card titles truncate

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/8accf91a-3a66-4e75-b0c2-7766e8fe20ce)

**Comment by askayastha22** [comment]
@coreydulimba-ad cannot replicate this issue.

**Comment by askayastha22** [comment]
@coreydulimba-ad https://experience.adobe.com/?shell_source=dev&ref=genai-plugin-dev&repo=wknd&owner=hlxsites&project=WKND#/@sitesinternal/aem/generate-variations/

**Comment by coreydulimba-ad** [comment]
fixed

**Comment by coreydulimba-ad** [comment]
deployed to prod
