### ISSUE TITLE
Update Variant States

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#155]
### Expected Behaviour

Update variant states to the following:

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/c11a8cbc-ef4e-481b-94c9-1c52f694d0b8)

NOTES: 
1. for hover do not use 400, use Gray-500 on hover then
2. in Active keep the shadow affect (thicker on bottom) that is currently in app

**Comment by askayastha22** [comment]
@coreydulimba-ad https://experience.adobe.com/?shell_source=dev&ref=genai-plugin-dev&repo=wknd&owner=hlxsites&project=WKND#/@sitesinternal/aem/generate-variations/

**Comment by coreydulimba-ad** [comment]
@askayastha22 can you do the treatment for favorites where a star is added to upper right? as opposed to making a yellow tint?
![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/953353c6-c99e-4775-8d8e-0567cde3f730)

**Comment by coreydulimba-ad** [comment]
Ashish Kayastha
  [4:45 PM](https://cq-dev.slack.com/archives/D04DJTGTNTU/p1702593909097299)
I left it as it is for a couple of reasons:
The yellow tint adds a nice visual indicator for the rectangular variant.
Adding a star to the top right is kind of redundant as we already show a shaded star in the variant preview below.
If first line is too long and fills to the end, the "star" icon would block the text.

**Comment by coreydulimba-ad** [comment]
will leave favorites as is for now

**Comment by coreydulimba-ad** [comment]
deployed to prod
