### ISSUE TITLE
Add a title to the popups

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#164]
### Expected Behaviour
Title of field should appear in pop up

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/28b63221-d55f-4ce2-af63-49130c42bbe9)

### Actual Behaviour
no title

**Comment by askayastha22** [comment]
@coreydulimba-ad https://experience.adobe.com/?shell_source=dev&ref=genai-plugin-dev&repo=wknd&owner=hlxsites&project=WKND#/@sitesinternal/aem/generate-variations/

**Comment by coreydulimba-ad** [comment]
approved

**Comment by coreydulimba-ad** [comment]
deployed to prod
