### ISSUE TITLE
Prompt results cut off

### ISSUE THREAD

**Issue by basecode** [adobe/aem-genai-assistant#170]
<img width="1315" alt="Screenshot 2023-12-05 at 13 23 31" src="https://github.com/adobe/aem-genai-assistant/assets/143527/1fb1c1c8-5afc-43b9-8e55-5881d598b465">

**Comment by coreydulimba-ad** [comment]
discussed with team on standup on 12.11 decided that this will occur in certain circumstances esp. once we start working with longer forms. 

Solution:
add "..." to end

**Comment by askayastha22** [comment]
@coreydulimba-ad https://experience-stage.adobe.com/?shell_ims=prod&ref=genai-plugin-dev&repo=wknd&owner=hlxsites&project=WKND#/@sitesinternal/aem/generate-variations/

**Comment by coreydulimba-ad** [comment]
approved

**Comment by coreydulimba-ad** [comment]
deployed to prod
