### ISSUE TITLE
load templates via .live and not .page 

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#176]
### Expected Behaviour
prompt templates load quickly 

### Actual Behaviour
I'm not seeing this but user reported take a long time to load

https://cq-dev.slack.com/archives/C04Q2CPDL86/p1701877264621009?thread_ts=1701804148.214049&cid=C04Q2CPDL86

tech suggestion:
Dylan DePass
  [27 minutes ago](https://cq-dev.slack.com/archives/C04Q2CPDL86/p1701877288209209?thread_ts=1701804148.214049&cid=C04Q2CPDL86)
 One suggestion. Since publishing the prompt-templates.json is part of the flow you are recommending to people then I would suggest to load them via .live and not .page . The cache headers returned on .live will be longer and the json will load faster from .live.

UX suggestion
we should also add a spinner or similar  here to let users know that the system is working if prompts are taking time to load

**Comment by vtsaplin** [comment]
The URL suffix (.page or .live) is determined by the Sidekick referrer URL, which is originally derived from the actual URL a customer uses for editing content. 

We have the option to explicitly replace .page with .live in the end of each url, which could shave off several hundred milliseconds from the loading time of spreadsheets. However, this approach required not only previewing each spreadsheet but also publishing them.

As there are no noticably perf difeferens, value are loaded layzily and it is only in authring env, I'd siggst to keep it as it is.

**Comment by coreydulimba-ad** [comment]
wont fix
