### ISSUE TITLE
Update information popup beside Generate

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#178]
### Expected Behaviour

legal needs updates to the 'i' next to generate follow instructions here

https://adobe-my.sharepoint.com/:w:/p/cdulimba/Ee4npp3Pz25JiAGnNSYFeRABjBqp6Zh7CyzCBU3-sdIRCw?e=68wj1g

**Comment by coreydulimba-ad** [comment]
@askayastha22 where should i review these QA?

**Comment by askayastha22** [comment]
> @askayastha22 where should i review these QA?

Yes

**Comment by coreydulimba-ad** [comment]
approved

**Comment by coreydulimba-ad** [comment]
deployed to prod
