### ISSUE TITLE
put new prompt card at end of prompt template

### ISSUE THREAD

**Issue by vtsaplin** [adobe/aem-genai-assistant#18]

**Comment by basecode** [comment]
"New Session" button was removed: https://github.com/adobe/aem-genai-assistant/commit/48211b98f1f319896d55612a2dd6362a89081eec

**Comment by coreydulimba-ad** [comment]
Title: New prompt
Description: To start a new prompt use this and then add it to your prompt templates for future use.

when select should go to location where the new session button went to

**Comment by basecode** [comment]
New Prompt Card: https://github.com/adobe/aem-genai-assistant/commit/6d33add3d1bffd063e21d8ccff3cd21bb7a107b7
