### ISSUE TITLE
break points for input panel

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#186]
### Expected Behaviour

create several break points based on screen size. have upper and lower bound

**Comment by askayastha22** [comment]
https://experience.adobe.com/?shell_source=dev&ref=genai-plugin-dev&repo=wknd&owner=hlxsites&project=WKND#/@sitesinternal/aem/generate-variations/

**Comment by coreydulimba-ad** [comment]
approved

**Comment by coreydulimba-ad** [comment]
deployed to prod
