### ISSUE TITLE
Desription text & icon not properly fitting 

### ISSUE THREAD

**Issue by nsdere** [adobe/aem-genai-assistant#31]
### Expected Behaviour
The text in the description under input fields does not properly fit within its designated area. 
If we are keeping the width of this area,  I would expect to see the full text displayed over multiple lines. 
Also the icon is different for text and number fields.
### Actual Behaviour
<img width="203" alt="image" src="https://github.com/adobe/aem-genai-assistant/assets/18396745/294a2d6b-fa39-47c6-af61-d7a6a627aa24">

**Comment by nsdere** [comment]
@vtsaplin removing` overflow: hidden `solves this issue but ruins the layout. should we add more padding between or limit the description?
<img width="228" alt="image" src="https://github.com/adobe/aem-genai-assistant/assets/18396745/a7468ccb-b762-4896-9761-fd5712a6b800">

**Comment by vtsaplin** [comment]
I think we need a UX solution for it
@kamendola

**Comment by coreydulimba-ad** [comment]
duplicate
