### ISSUE TITLE
update URL for user guidelines

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#35]
### Expected Behaviour
legal disclaimer should point to https://www.adobe.com/legal/licenses-terms/adobe-dx-gen-ai-user-guidelines.html

### Actual Behaviour
it points to  https://www.adobe.com/legal/licenses-terms/adobe-gen-ai-user-guidelines.html

**Comment by roribio** [comment]
@coreydulimba-ad [Updated the link](https://github.com/adobe/aem-genai-assistant/commit/b286663ad8a1878dd6328c08e601c2e99b02ad48) as requested but, the link seems to be broken.

Please advise.

**Comment by coreydulimba-ad** [comment]
@roribio yes link needs updated by the a.com team but we don't need to worry about that now

**Comment by roribio** [comment]
Closing per the following:

> Corey Dulimba
>   [1 day ago](https://magento.slack.com/archives/C050XSQ2BCN/p1700145063636899?thread_ts=1700099567.252949&cid=C050XSQ2BCN)
> I just got a new legal link its https://www.adobe.com/legal/licenses-terms/adobe-dx-gen-ai-user-guidelines.html this should be in the user consent model and in the product under "user guidelines"
> Please note that we are still finalizing the Guidelines language that will be published at the URL so if you happen to click through the link right now it will appear to be “broken.” We will update you once the Guidelines have been published to the URL.

https://magento.slack.com/archives/C050XSQ2BCN/p1700145063636899?thread_ts=1700099567.252949&cid=C050XSQ2BCN
