### ISSUE TITLE
update consent modal with image and new wording from legal

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#40]
### Expected Behaviour

Image:

the Firefly consent has an image like this
![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/9324ae8e-9774-4e99-91f7-09ecbd40346d)

can we use the tree image we are using in the assistant and put it on top of the consent model like firefly has for the bird?
![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/56800a5d-25ca-44b0-a61d-a6177a53c2a3)

text:
updated based on this copy
https://adobe-my.sharepoint.com/:w:/p/cdulimba/Ee4npp3Pz25JiAGnNSYFeRABjBqp6Zh7CyzCBU3-sdIRCw?e=DtQrE8

### Actual Behaviour

add image and update copy

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/b1f657a7-ef37-425e-96e7-e6102ac68aaa)

**Comment by askayastha22** [comment]
https://experience.adobe.com/?shell_source=dev&ref=genai-plugin-dev&repo=wknd&owner=hlxsites&project=WKND#/@sitesinternal/aem/generate-variations/

To test please switch to an IMS org that you haven't agreed to the consent dialog.

**Comment by coreydulimba-ad** [comment]
approved

**Comment by coreydulimba-ad** [comment]
deployed to prod
