### ISSUE TITLE
Prompt input tooltip does not wrap around

### ISSUE THREAD

**Issue by roribio** [adobe/aem-genai-assistant#44]
### Expected Behaviour
An input field's tooltip should be fully displayed in some way even if the text length exceeds the width of the Input form panel. 

### Actual Behaviour
If a tooltip's lenght exceeds the width of the Input form panel, the text does not wrap around.

<img width="319" alt="Screenshot 2023-11-17 at 7 59 39 AM" src="https://github.com/adobe/aem-genai-assistant/assets/1751465/c611af8e-b3b1-43f9-9568-4dd0146638e4">

**Comment by coreydulimba-ad** [comment]
https://react-spectrum.adobe.com/react-spectrum/ContextualHelp.html

move the icon next to label and use tool tip
