### ISSUE TITLE
Temperature slide scale goes from 0 to 0.9 and change default 

### ISSUE THREAD

**Issue by roribio** [adobe/aem-genai-assistant#47]
### Expected Behaviour
The temperature on gpt-4 goes from 0 to 2.

DEFAULT should be 1

See: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions

### Actual Behaviour
The temperature on gpt-4 goes from 0 to 0.9.

**Comment by roribio** [comment]
I thought we had landed on giving the whole range but providing defaults at set points? Either way the scale is wrong because in our testing we found best results between 1 and 1.2

**Comment by coreydulimba-ad** [comment]
@roribio also the default is .1 that a good default? when running prompting sessions what is the default you use? seems like .1 is to low?

**Comment by roribio** [comment]
Closed by #119
