### ISSUE TITLE
Navigating to a recent session from another prompt shows empty inputs

### ISSUE THREAD

**Issue by roribio** [adobe/aem-genai-assistant#48]
### Expected Behaviour
If I click on a recent session, I expect the prompt and inputs to be filled no matter where I was before in the assistant.

### Actual Behaviour
If I click on a prompt and then try to navigate to a recent session the inputs are empty.

<img width="703" alt="Screenshot 2023-11-17 at 8 24 20 AM" src="https://github.com/adobe/aem-genai-assistant/assets/1751465/79d98100-d6dc-4a11-b914-b824a035cb6b">

#### Steps to Reproduce
- start a session
- fill inputs
- generate something
- Go to the homepage
- Click on a prompt
- Click on a recent session
- Inputs should appear empty

**Comment by coreydulimba-ad** [comment]
cannot reproduce
