### ISSUE TITLE
Rename Audience Segment file in code

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#50]
### Expected Behaviour

code should read "audience_segments" as file will be named this to more descriptive

### Actual Behaviour
code is looking for "segments"

Open Question??
do we need a version for Google Sheets or code doesn't care about the format?

**Comment by roribio** [comment]
Addressing this issue on PR #120.

**Comment by roribio** [comment]
PR #120 is merged and closed.
