### ISSUE TITLE
Google Sheet Support

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#51]
### Expected Behaviour
EDS supports both GDrive and Sharepoint so we need templates for prompts and audience segments in both formats

Questions
1. if using Google Sheets for templates does the app need changed?

**Comment by coreydulimba-ad** [comment]
2 promptTemplates
1. excel
2. Sheets

finalize where we will put these and provide link for docs

**Comment by roribio** [comment]
@coreydulimba-ad 

I did some testing:

1. The only way that's available to programmatically generate Google Spreadsheets is authenticating with their API.
2. Google Spreadsheets can open Excel and CSV files but they're not automatically converted to a Google Spreadsheet files.
3. AEM Sidekick does not allow generating previews from Excel files in GDrive, it has to be converted to GDocs format first.

So, we're not going to provide two template formats. We're only going to provide the Excel format.

For GDrive users, we need to add to the docs the following:

1. The template files must be downloaded from our Github repo in Excel format under `examples/` directory. The templates will be available as individual files and/or `templates.zip`.
2. The Excels must be uploaded to GDrive
3. Then each file must be opened and "File>Save as Google Spreadsheet"
4. Preview and Publish each file.
