### ISSUE TITLE
Ensure that Adobe logo only shows up for our templates and not when customer adds a prompt

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#57]
### Expected Behaviour

the Adobe logo only shows up for Adobe provided templates

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/50b4c9bb-4c65-448e-b5cc-d1c71fb0120c)

### Actual Behaviour

I'm not sure the logic here. when a cusstomer saves a prompt will teh Adobe logo show???

**Comment by coreydulimba-ad** [comment]
@nsdere can you check?

**Comment by coreydulimba-ad** [comment]
2 spreadsheets
1. for customer templates
2. for adobe. we will host this -- advantage is that as we add prompt they will show

**Comment by nsdere** [comment]
Adobe prompts [(see the prompts)](https://github.com/adobe/aem-genai-assistant/blob/main/docs/bundledPromptTemplates.json) have Adobe logo, while those edited in the promptTemplates do not include the logo.
![image](https://github.com/adobe/aem-genai-assistant/assets/18396745/94cbc221-745b-4ade-9fb1-aa11873e85dd)
