### ISSUE TITLE
Update left nav and home page with branding

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#58]
### Expected Behaviour

please update according the below

<img width="1144" alt="image" src="https://github.com/adobe/aem-genai-assistant/assets/41452765/ea903f8d-e24a-402e-84f9-71b770ab64aa">

**Comment by basecode** [comment]
https://github.com/adobe/aem-genai-assistant/commit/f5335520805cee03e80ecc9705e3e7ed29cc9108

**Comment by ddragosd** [comment]
cherry-picked this in #72
