### ISSUE TITLE
Error code support

### ISSUE THREAD

**Issue by basecode** [adobe/aem-genai-assistant#61]
- [x] 400 https://github.com/adobe/aem-genai-assistant/commit/4c7fad0eb1223c165662a520a9797b32d568c892
- [x] 401 & 403
- [x] IS-ERROR
- [x] AEM-ERROR
- [x] AIO-ERROR
- [x] Default

**Comment by basecode** [comment]
Feedback API: https://github.com/adobe/aem-genai-assistant/commit/eae9a5cb8f49777ff9fb79d336ecb08151a70427

**Comment by roribio** [comment]
PR: #166
