### ISSUE TITLE
Update config setup instructions based on new name

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#62]
### Expected Behaviour

"Generate Content Variations" should be title and ID. please update and supply the new config

### Actual Behaviour

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/39e5ab56-5af5-49c6-a399-1fee7b87e4f6)

**Comment by basecode** [comment]
Fixed in readme: https://github.com/adobe/aem-genai-assistant/commit/e2a0a7e518eacabeea3f865cfce34d5909415ec8
Still requires fix in public docs.

**Comment by coreydulimba-ad** [comment]
updated
