### ISSUE TITLE
Copy prompt result is not compatible with word editor

### ISSUE THREAD

**Issue by basecode** [adobe/aem-genai-assistant#63]
![Screenshot 2023-11-20 at 17 53 56](https://github.com/adobe/aem-genai-assistant/assets/143527/1fc57e5f-03bb-4cc8-86d2-09ef697b4830)

**Comment by coreydulimba-ad** [comment]
@basecode if you close something does that mean its deployed or still needs to be deployed? Just checked QA and fix is not there.
