### ISSUE TITLE
customer is forced have a segment

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#64]
### Expected Behaviour

customer can decide if they want select an audience segment or not

potential fix is for the first row in document to be "select an option"

### Actual Behaviour

customer is defaulted to a selection and is forced to use one

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/99b3d61e-a251-4318-9080-921c6817de0f)

**Comment by coreydulimba-ad** [comment]
![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/41dda34c-3f33-4945-ab78-7cfd871a408d)

**Comment by roribio** [comment]
This issues is addressed by PR #120 but is being tracked on issue #50
