### ISSUE TITLE
Remove copy icon from prompt and change re-use icon

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#66]
### Expected Behaviour

1 copy button (not 2), re-use to have a different icon so when we introduce save button its not duplicated

- remove the prompt copy
- change logo for re-use >> killian will supply new icon
### Actual Behaviour

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/6a7c40e8-b839-49bd-ac2c-37aa58f3b358)

**Comment by kamendola** [comment]
Please use Spectrum icon "Refresh"

**Comment by coreydulimba-ad** [comment]
fixed
