### ISSUE TITLE
Formatting is not preserved in Favorites

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#67]
### Expected Behaviour
formatting from prompt screen is preserved to favorites

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/3e5245e3-b45e-4dd5-83f2-bd10db86aed3)

### Actual Behaviour

formatting not correct

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/12318dfc-e92e-4f80-8420-8e99a72be84b)

**Comment by basecode** [comment]
Fixed with #79

**Comment by coreydulimba-ad** [comment]
@basecode if you close does that mean its deployed to QA? i dont' see fix in QA

**Comment by basecode** [comment]
@coreydulimba-ad no, it means it has been merged to `main`. But I requested a deployment to QA in parallel, meaning it is on QA now.
