### ISSUE TITLE
Add prompt indicator on Favorites 

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#69]
### Expected Behaviour

able to identify where the favoriate variant came from

perhaps add a tag with the prompt name, this would also allow the user to select the prompt again from recents as well

### Actual Behaviour

no way to discern where the favorite came from

![image](https://github.com/adobe/aem-genai-assistant/assets/41452765/b0f6bbf4-c778-435a-a321-e3f430e947ea)

**Comment by vtsaplin** [comment]
This one requires detailed clarification, as its implementation is decently complicated. 
- Can it be excluded from MVP scope? 
- If not, what precisely do we need to add to the card (text, buttons, etc.)? What should happen when a user clicks a button?

cc @kamendola @coreydulimba-ad

**Comment by coreydulimba-ad** [comment]
@vtsaplin not needed for MVP. there is actually not a MVP tag on it :)
