### ISSUE TITLE
Fix Errors and remove debug logs in dev console

### ISSUE THREAD

**Issue by basecode** [adobe/aem-genai-assistant#81]
![Screenshot 2023-11-22 at 10 43 58](https://github.com/adobe/aem-genai-assistant/assets/143527/031afe58-3107-4657-bacf-0671f4debdcc)

**Comment by basecode** [comment]
Looks good!

**Comment by vtsaplin** [comment]
I am reopening the issue. To-dos:
- Fix JS errors.
- Move the error mapping code to the backend.

**Comment by basecode** [comment]
@vtsaplin not sure this ticket is related and worth re-opening. What do you think about using #168?
