### ISSUE TITLE
Match top of "home page" with mocks

### ISSUE THREAD

**Issue by coreydulimba-ad** [adobe/aem-genai-assistant#95]
### Expected Behaviour

match the image with grey background, headline, and subheading to mocks

<img width="1488" alt="image" src="https://github.com/adobe/aem-genai-assistant/assets/41452765/cf5351ff-1904-49a4-bdb6-9864d809d548">

https://www.figma.com/proto/WF6g8VF9DaaxIXOiCzWpQp/AEM-GenAI-Assistant?page-id=495%3A19574&type=design&node-id=495-24175&viewport=1245%2C507%2C0.33&t=qC882XmBpODTvSHM-1&scaling=min-zoom&starting-point-node-id=509%3A4099

### Actual Behaviour

<img width="1585" alt="image" src="https://github.com/adobe/aem-genai-assistant/assets/41452765/0cbc5f8c-7ad0-4547-bedb-cb8d1fec7dcb">

**Comment by basecode** [comment]
Fixed by https://github.com/adobe/aem-genai-assistant/pull/111

**Comment by coreydulimba-ad** [comment]
fixed
